---
- name: demo configuration
  hosts: all
  become: yes
  become_user: root

  vars:
    required_packages: ['python3',
                        'ansible',
                        'docker']

  tasks:
    - name: install packages
      yum:
        name: "{{ required_packages }}"
        state: latest

    - name: cockpit install & config
      include_role:
        name: linux-system-roles.cockpit
      vars:
        cockpit_packages: full
        cockpit_enabled: yes
        cockpit_started: yes
        cockpit_config:
          WebService:
            Origins: "https://centos-demo.example.com"
            LoginTitle: "Welcome to demo"
            ProtocolHeader: "X-Forwarded-Proto"
            AllowUnencrypted: true

    - name: nginx user
      user:
        name: nginx
        group: nginx
        shell: /sbin/nologin
        state: present

    - name: certificate creation
      include_role:
        name: linux-system-roles.certificate
      vars:
        certificate_requests:
          - name: centos-demo
            dns: centos-demo.example.com
            ca: self-sign
            owner: nginx
            group: nginx

    - name: nginx proxy
      include_role:
        name: geerlingguy.nginx
      vars:
        nginx_user: "nginx"
        nginx_vhosts:
          - listen: "443 ssl http2"
            server_name: "centos-demo.example.com"


            state: "present"
            template: "{{ nginx_vhost_template }}"
            filename: "example.com.conf"
            extra_parameters: |
              location / {
                proxy_pass https://127.0.0.1:9090;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
        
                # Required for web sockets to function
                proxy_http_version 1.1;
                proxy_buffering off;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        
                # Pass ETag header from Cockpit to clients.
                # See: https://github.com/cockpit-project/cockpit/issues/5239
                gzip off;
              }
              ssl_certificate     /etc/pki/tls/certs/centos-demo.crt;
              ssl_certificate_key /etc/pki/tls/private/centos-demo.key;
              ssl_protocols       TLSv1.1 TLSv1.2;
              ssl_ciphers         HIGH:!aNULL:!MD5;

    - name: selinux
      seboolean:
        name: 'httpd_can_network_connect'
        persistent: yes
        state: true



    - name: firewall cockpit config
      include_role:
        name: linux-system-roles.firewall
      vars:
        firewall:
          service: cockpit
          state: disabled

    - name: firewall nginx config
      include_role:
        name: linux-system-roles.firewall
      vars:
        firewall:
          service: https
          state: enabled

    - name: nginx_restart
      service:
        name: nginx
        state: restarted



